services:
    _defaults:
        public: true

    bitbag_sylius_mollie_plugin.controller.action.admin.refund:
        class: BitBag\SyliusMolliePlugin\Controller\Action\Admin\Refund
        arguments:
            - "@sylius.repository.payment"
            - "@payum"
            - "@session"
            - "@sm.factory"
            - "@sylius.manager.payment"
