services:
    bitbag_sylius_mollie_plugin.form.type.mollie_gateway_configuration:
        class: BitBag\SyliusMolliePlugin\Form\Type\MollieGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: mollie, label: bitbag_sylius_mollie_plugin.ui.mollie_gateway_label }
            - { name: form.type }

    bitbag_sylius_mollie_plugin.form.type.mollie_subscription_gateway_configuration:
        class: BitBag\SyliusMolliePlugin\Form\Type\MollieSubscriptionGatewayConfigurationType
        tags:
            - { name: sylius.gateway_configuration_type, type: mollie_subscription, label: bitbag_sylius_mollie_plugin.ui.mollie_subscription_gateway_label }
            - { name: form.type }

    bitbag_sylius_mollie_plugin.form.type.direct_debit:
        class: BitBag\SyliusMolliePlugin\Form\Type\DirectDebitType
        arguments:
            - "@session"
        tags:
            - { name: form.type }

    bitbag_sylius_mollie_plugin.form.extension.complete_type:
        class: BitBag\SyliusMolliePlugin\Form\Extension\CompleteTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\CoreBundle\Form\Type\Checkout\CompleteType }
