services:
    bitbag_sylius_mollie_plugin.gateway_factory.mollie:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments:
            -  BitBag\SyliusMolliePlugin\MollieGatewayFactory
        tags:
            - { name: payum.gateway_factory_builder, factory: mollie }
