version: '3.9'

services:
  browser:
    container_name: browser
    ports:
      - "9222:9222"
    build:
      context: .docker/
      dockerfile: Dockerfile.chromium
    command: "http://127.0.0.1"

  hub:
    container_name: selenium-hub
    image: selenium/hub:3.11.0
    ports:
      - "4444:4444"
    links:
      - app

  chrome:
    container_name: selenium-chrome
    image: selenium/node-chrome-debug:3.11.0
    depends_on:
      - hub
    links:
      - app
    environment:
      - HUB_HOST=hub
      - HUB_PORT=4444
    ports:
         - "5900:5900"
  app:
    build:
        context: .docker/
    container_name: sylius-mollie5-dev
    tty: true
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "2222:22"
    volumes:
      - "mollie_db_volume:/var/lib/mysql"
      - ./.:/var/www/html/public:rw
      - ./tests/Application/public/media:/var/www/html/public/tests/Application/public/media:rw
    environment:
      - XDEBUG_ENABLED=1
      - XDEBUG_REMOTE_HOST=172.17.0.1
      - PHP_VERSION=8.0
      - NODE_VERSION=14

volumes:
  mollie_db_volume:
    name: mollie_db_volume