imports:
    - { resource: "services/form.yml" }
    - { resource: "services/gateway_factory.yml" }
    - { resource: "services/action.yml" }
    - { resource: "services/validators.yml" }
    - { resource: "services/controller.yml" }
    - { resource: "services/payment_processing.yml" }

services:
    bitbag_sylius_mollie_plugin.mollie_api_client:
        class: BitBag\SyliusMolliePlugin\Client\MollieApiClient

    bitbag_sylius_mollie_plugin.get_http_request:
        class: Payum\Core\Request\GetHttpRequest
