bitbag_sylius_mollie_plugin_payment_fee_calculate:
  path: /payment-fee-calculate/{methodId}
  defaults:
    _controller: bitbag_sylius_mollie_plugin.controller.action.shop.payment_fee_calculate_action
