sylius_resource:
    resources:
        sylius_mollie_plugin.mollie_subscription_schedule:
            driver: doctrine/orm
            classes:
                model: SyliusMolliePlugin\Entity\MollieSubscriptionSchedule
                interface: SyliusMolliePlugin\Entity\MollieSubscriptionScheduleInterface
