sylius_resource:
  resources:
    sylius_mollie_plugin.template_mollie_email:
      driver: doctrine/orm
      classes:
        model: SyliusMolliePlugin\Entity\TemplateMollieEmail
        interface: SyliusMolliePlugin\Entity\TemplateMollieEmailInterface
        form: SyliusMolliePlugin\Form\Type\TemplateMollieEmailType
      translation:
        classes:
            model: SyliusMolliePlugin\Entity\TemplateMollieEmailTranslation
            interface: SyliusMolliePlugin\Entity\TemplateMollieEmailTranslationInterface
            repository: SyliusMolliePlugin\Repository\TemplateMollieEmailTranslationRepository
