sylius_resource:
  resources:
    sylius_mollie_plugin.mollie_gateway_config:
      driver: doctrine/orm
      classes:
        model: SyliusMolliePlugin\Entity\MollieGatewayConfig
        repository: SyliusMolliePlugin\Repository\MollieGatewayConfigRepository
      translation:
        classes:
          model: SyliusMolliePlugin\Entity\MollieGatewayConfigTranslation
          interface: SyliusMolliePlugin\Entity\MollieGatewayConfigTranslationInterface
