sylius_resource:
    resources:
        sylius_mollie_plugin.mollie_subscription:
            driver: doctrine/orm
            classes:
                model: SyliusMolliePlugin\Entity\MollieSubscription
                interface: SyliusMolliePlugin\Entity\MollieSubscriptionInterface
                repository: SyliusMolliePlugin\Repository\MollieSubscriptionRepository
