sylius_resource:
  resources:
    sylius_mollie_plugin.mollie_customer:
      driver: doctrine/orm
      classes:
        model: SyliusMolliePlugin\Entity\MollieCustomer
        interface: SyliusMolliePlugin\Entity\MollieCustomerInterface
