sylius_resource:
    resources:
        sylius_mollie_plugin.product_type:
            driver: doctrine/orm
            classes:
                model: SyliusMolliePlugin\Entity\ProductType
                interface: SyliusMolliePlugin\Entity\ProductTypeInterface
                form: SyliusMolliePlugin\Form\Type\ProductTypeType
