mollie_admin_methods:
  path: /mollie/methods/{id}/all
  methods: [GET]
  defaults:
    _controller: sylius_mollie_plugin.controller.action.admin.methods
  requirements:
    id: '\d+'

mollie_admin_test_api_keys:
  path: /mollie/methods/test
  methods: [GET]
  defaults:
    _controller: sylius_mollie_plugin.controller.action.admin.test_api_keys_action

mollie_admin_change_position:
  path: /mollie/methods/change-position
  methods: [GET]
  defaults:
    _controller: sylius_mollie_plugin.controller.action.admin.change_position_payment_method_action
